package edu.curtin.saed.parser;
/* Generated By:JavaCC: Do not edit this line. GameInputParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GameInputParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SIZE = 1;
  /** RegularExpression Id. */
  int START = 2;
  /** RegularExpression Id. */
  int GOAL = 3;
  /** RegularExpression Id. */
  int ITEM = 4;
  /** RegularExpression Id. */
  int OBSTACLE = 5;
  /** RegularExpression Id. */
  int AT = 6;
  /** RegularExpression Id. */
  int MESSAGE = 7;
  /** RegularExpression Id. */
  int REQUIRES = 8;
  /** RegularExpression Id. */
  int PLUGIN = 9;
  /** RegularExpression Id. */
  int SCRIPT = 10;
  /** RegularExpression Id. */
  int LBRACE = 11;
  /** RegularExpression Id. */
  int RBRACE = 12;
  /** RegularExpression Id. */
  int EXCLAMATION_BRACE = 13;
  /** RegularExpression Id. */
  int LPAREN = 14;
  /** RegularExpression Id. */
  int RPAREN = 15;
  /** RegularExpression Id. */
  int COMMA = 16;
  /** RegularExpression Id. */
  int QUOTE = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;
  /** RegularExpression Id. */
  int STRING = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"size\"",
    "\"start\"",
    "\"goal\"",
    "\"item\"",
    "\"obstacle\"",
    "\"at\"",
    "\"message\"",
    "\"requires\"",
    "\"plugin\"",
    "\"script\"",
    "\"{\"",
    "\"}\"",
    "\"!{\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"\\\"\"",
    "<DIGIT>",
    "<STRING>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 24>",
    "\".\"",
    "<token of kind 26>",
  };

}
